config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources :users, only: [:index, :show]
  resources :menus
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i # [a-z\d]は英数字,{6,}は下限と上限、/iは大文字も小文字も含む
  VALID_NAME_REGEX = /\A[ぁ-んァ-ン一-龥々]+[a-zA-Z]+\z/ # 全角ひらがな、カタカナ、漢字
  VALID_PHONENUMBER_REGEX = /\A\d{10,11}\z/ # ハイフンなし10桁or11桁電話番号

  with_options presence: true do
    validates :shop_name
    validates :owner_name
    validates :owner_phone_number,  format: { with: VALID_PHONENUMBER_REGEX }
    validates :shop_address
    validates :shop_city
  end

  validates :password, format: { with: VALID_PASSWORD_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:shop_name, :owner_name, :owner_phone_number, :shop_address, :shop_city, :email])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to action: :index

    else
      render :new
    end

  end

  private
  def menu_params
    params.require(:menu).permit(:name, :price).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  
  def index
    @users = User.all.order('shop_city DESC')
  end

  def show
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileChumon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
<%= render "shared/header" %>
index
<%= link_to 'メニュー登録', new_menu_path %>
<%= render "shared/footer" %>

app/views/menus/new.html.erb
<%= render "shared/header" %>

<%= form_with model:@menu, local: true do |f| %>
<%#= render 'shared/error_messages', model: f.object %>
<div class="menu-name">
  名前
  <%= f.text_field :name%>
</div>
<div class="menu-name">
  値段
  <%= f.text_field :price%>
</div>
<div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
<% end %>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='top-page-footer'>
  <h2 class='footer-message'>
    お店の方はこちらから！
  </h2>
  <div clss='footer-navigate'>
    <ul class='nav'>
    <% if user_signed_in? %>

    <li class='navi-list'>
      <%= link_to "#{current_user.shop_name}のマイページ", "", class:"user-link" %>
    </li>

    <li class='navi-list'>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"user-link" %>
    </li>

    <% else %>
    <li class='navi-list'>
      <%= link_to '新規登録', new_user_registration_path, class:"user-link" %>
    </li>
    <li class='navi-list'>
      <%= link_to 'ログイン', new_user_session_path, class:"user-link" %>
    </li>
    <% end %>
    
    </ul> 
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='logo'>
    <%= link_to image_tag("chumon-header.png", class:"logo-image"), "/" %>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_second_footer.html.erb
<footer class='top-page-footer'>
  <div clss='footer-navigate'>
    <% if user_signed_in? %>

    <h3>ログイン中</h3>
    <% end %>
    

  </div>
</footer>

app/views/users/index.html.erb
<%= render "shared/header" %>

<div class='main'>
  <div class='service-explain'>
    <%= image_tag("smartphone1.png", class:"phone-image") %>

    <h2 class='explain-text'>
      スマホからのご注文を<br>お待ちしています！
    <br><br>
      店員を呼ばずにスマホから
    <br>
      ご注文、お支払いいただけます
    </h2>
  </div>

  <div class='contetns'>
  <h1 class='title'>
    利用できる店舗一覧
  </h1>

  <ul class='shop-lists'>
    <% @users.each do |user| %>
        <li class='list'>
          <%= link_to user_path(user.id) do %>
            <div class='shop-info'>
              <h3><%= user.shop_city %></h3>
            </div>
            <div class='shop-info'>
              <h3><%= user.shop_name %></h3>
            </div>
          <% end %>
        </li>
     <% end %>
    </ul>

  </div>
</div>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<h1>show</h1>
<%= render 'shared/second_footer' %>